import fs from "node:fs/promises";
import { ChangelogEntry, parseChangelogFile } from "../changelog/parse";
import { TegamiContext } from "../context";
import { validateChangelogStore, validatePackageStore } from "./draft";
import { parsePublishLock, PublishLock } from "./lock";
import type { Awaitable, PublishPreflight, TegamiPlugin } from "../types";
import { WorkspacePackage } from "../graph";
import { handlePluginError } from "../utils/error";
import { findPromiseIndex, somePromise } from "../utils/common";

export interface PublishPlan {
  options: PublishOptions;

  /** id -> entry */
  changelogs: Map<string, ChangelogEntry>;
  /** id -> package data. The package id will always exist in package graph, stale items will be pruned at init-time */
  packages: Map<string, PackagePublishPlan>;

  /** every publish task of the run */
  tasks: readonly PublishTask[];

  /** the packages of the plan that should publish, resolved by preflights */
  getPackagesToPublish(): WorkspacePackage[];

  /** generated by GitHub/GitLab plugin (internal) */
  $versionRequest?: {
    publishGroups: Map<string, "active" | "pending">;
  };
}

export interface PackagePublishPlan {
  changelogs: ChangelogEntry[];
  /** whether this package was version-bumped when the lock was written */
  updated: boolean;

  /** generated by Git plugin */
  git?: {
    /** the associated Git tag of package */
    tag?: string;
  };

  /** generated by npm plugin */
  npm?: {
    /** dist tag to use if published */
    distTag?: string;

    /** point latest tag to it if published */
    markLatest?: boolean;
  };

  /**
   * Publish result, derived from the package's publish tasks: `undefined` until they
   * settle, `skipped` for packages without a publish task.
   */
  readonly publishResult?: PackagePublishResult;

  /** preflight result, generated for all packages in publish plan after preflights */
  preflight?: PublishPreflight;
}

export async function initPublishPlan(
  context: TegamiContext,
  options: PublishOptions,
): Promise<PublishPlan | undefined> {
  let lock: PublishLock;
  try {
    lock = parsePublishLock(await fs.readFile(context.lockPath, "utf8"));
  } catch {
    return;
  }

  let data: unknown;
  const packages = new Map<string, PackagePublishPlan>();
  const changelogs = new Map<string, ChangelogEntry>();
  const plan: PublishPlan = {
    options,
    changelogs,
    packages,
    tasks: [],
    getPackagesToPublish() {
      const result: WorkspacePackage[] = [];

      for (const [id, packagePlan] of packages) {
        if (!packagePlan.preflight?.shouldPublish) continue;
        const pkg = context.graph.get(id);
        if (pkg) result.push(pkg);
      }

      return result;
    },
  };

  while ((data = lock.read("core:changelogs"))) {
    const validated = validateChangelogStore(data);
    if (!validated.success) continue;
    const entry = validated.data;
    const parsed = parseChangelogFile(entry.filename, entry.content);
    if (!parsed) continue;

    changelogs.set(parsed.id, parsed);
  }

  while ((data = lock.read("core:packages"))) {
    const validated = validatePackageStore(data);
    if (!validated.success) continue;
    const parsed = validated.data;
    if (!context.graph.get(parsed.id)) continue;

    const pkgChangelogs: ChangelogEntry[] = [];
    for (const id of parsed.changelogIds ?? []) {
      const entry = changelogs.get(id);
      if (entry) pkgChangelogs.push(entry);
    }
    packages.set(parsed.id, {
      changelogs: pkgChangelogs,
      updated: parsed.updated,
      get publishResult(): PackagePublishResult | undefined {
        if (!this.preflight) return;
        if (!this.preflight.shouldPublish) return { type: "skipped" };

        for (const task of plan.tasks) {
          if (!(task instanceof PackagePublishTask) || task.pkg.id !== parsed.id) continue;

          const state = task.getResult();
          if (!state) return;
          if (state.status === "failed")
            return { type: "failed" as const, error: state.error.message };
          return state.result;
        }

        return { type: "skipped" };
      },
    });
  }

  for (const plugin of context.plugins) {
    await handlePluginError(plugin, "initPublishPlan", () =>
      plugin.initPublishPlan?.call(context, { lock, plan }),
    );
  }

  return plan;
}

/** additional metadata of publish tasks, can be extended from other places */
export interface PublishTaskMetadata {}

export interface PublishTaskContext {
  context: TegamiContext;
  plan: PublishPlan;
}

export type PublishTaskRunContext = PublishTaskContext;

// merge the optional metadata fields into the class, safe since every member is optional
// oxlint-disable-next-line no-unused-vars, no-unsafe-declaration-merging
export interface PublishTask<T = unknown> extends PublishTaskMetadata {}

export abstract class PublishTask<T = unknown> {
  /** a short title for the task */
  abstract name: string;
  /** describe the purpose of the task */
  description?: string;
  /**
   * Tasks that must settle before this one runs, they must be part of the publish tasks,
   * and circular `wait` relationships are rejected with an error. Duplicated items are allowed.
   *
   * Failed tasks don't prevent this task from running, inspect them with `getResult`.
   */
  wait: PublishTask[] = [];
  /**
   * Like `wait`, but the waited tasks may not be part of the publish tasks (ignored),
   * and edges that close a dependency cycle are dropped to break the cycle.
   */
  optionalWait: PublishTask[] = [];

  /** @internal set by the task runner when the task settles */
  $state?: PublishTaskState<T>;

  /** @internal task instances are single-use */
  $started = false;

  /** inspect the outcome of the task, `undefined` when the task has not settled */
  getResult(): PublishTaskState<T> | undefined {
    return this.$state;
  }

  abstract run(opts: PublishTaskRunContext): Awaitable<T>;

  /** link task-level dependencies, called after every task is created */
  link?(opts: PublishTaskContext): void;

  /**
   * Check if the task's effects are already applied (e.g. from a previous run), without running it.
   *
   * Used to resolve publish plan status, return nothing when the task has no opinion.
   */
  status?(opts: PublishTaskContext): Awaitable<"done" | "pending" | void | undefined>;
}

export type PublishTaskState<T = unknown> =
  | { status: "success"; result: T }
  | { status: "failed"; error: Error };

/**
 * Run tasks concurrently, respecting their `wait` & `optionalWait` relationships
 * (see {@link scheduleTasks} for how cycles are resolved).
 *
 * Failed tasks never prevent dependents from running, tasks can inspect the outcome of
 * their waited tasks with `getResult` and decide on their own.
 *
 * Errors thrown by tasks are captured into the task states, never thrown. Task instances
 * are single-use; publish hooks create a fresh graph for every run.
 */
export async function runPublishTasks(
  tasks: PublishTask[],
  {
    context,
    plan,
    concurrency = 5,
  }: {
    context: TegamiContext;
    plan: PublishPlan;
    /** max amount of concurrently running tasks */
    concurrency?: number;
  },
): Promise<void> {
  if (!Number.isSafeInteger(concurrency) || concurrency < 1) {
    throw new RangeError(`Task concurrency must be a positive integer, received ${concurrency}.`);
  }

  const schedule = scheduleTasks(tasks);
  for (const task of schedule.keys()) {
    if (task.$started) {
      throw new Error(
        `Publish task "${task.name}" has already been run; task instances are single-use.`,
      );
    }
  }
  for (const task of schedule.keys()) task.$started = true;

  const runContext: PublishTaskRunContext = { plan, context };

  async function run(task: PublishTask) {
    try {
      task.$state = { status: "success", result: await task.run(runContext) };
    } catch (e) {
      task.$state = {
        status: "failed",
        error: e instanceof Error ? e : new Error(String(e)),
      };
    }
  }

  const remainingDeps = new Map<PublishTask, number>();
  const dependents = new Map<PublishTask, PublishTask[]>();
  const ready: PublishTask[] = [];
  for (const [task, deps] of schedule) {
    remainingDeps.set(task, deps.length);
    if (deps.length === 0) ready.push(task);
    for (const dep of deps) {
      const list = dependents.get(dep) ?? [];
      list.push(task);
      dependents.set(dep, list);
    }
  }

  let readyIndex = 0;
  let running = 0;
  let settled = 0;
  const completed: PublishTask[] = [];
  let notify: (() => void) | undefined;

  function start(task: PublishTask) {
    running++;
    void run(task).then(() => {
      completed.push(task);
      notify?.();
      notify = undefined;
    });
  }

  while (settled < schedule.size) {
    while (running < concurrency && readyIndex < ready.length) start(ready[readyIndex++]!);

    if (completed.length === 0) {
      await new Promise<void>((resolve) => {
        notify = resolve;
      });
    }

    for (const task of completed.splice(0)) {
      running--;
      settled++;

      for (const dependent of dependents.get(task) ?? []) {
        const count = remainingDeps.get(dependent)! - 1;
        remainingDeps.set(dependent, count);
        if (count === 0) ready.push(dependent);
      }
    }
  }
}

/**
 * The returned map iterates in execution order (a topological order of the dependency
 * graph), each task mapped to the dependencies it waits for at run-time.
 */
function scheduleTasks(tasks: PublishTask[]): Map<PublishTask, PublishTask[]> {
  const taskSet = new Set(tasks);
  if (taskSet.size !== tasks.length) {
    throw new Error("The publish task list contains the same task instance more than once.");
  }
  const resolved = new Map<PublishTask, PublishTask[]>();
  const stack: PublishTask[] = [];
  const stackIndex = new Map<PublishTask, number>();
  /** edge kinds from `stack[i]` to `stack[i + 1]` */
  const stackEdges: boolean[] = [];

  /** returns `false` when the edge to this task must be dropped to break a cycle */
  function scan(task: PublishTask, requiredEdge?: boolean): boolean {
    const cycleStart = stackIndex.get(task);
    if (cycleStart !== undefined) {
      const cycleHasRequiredEdge =
        requiredEdge === true || stackEdges.slice(cycleStart).includes(true);
      if (cycleHasRequiredEdge) {
        throw new Error(
          `circular reference of deps: ${[...stack.slice(cycleStart), task]
            .map((t) => t.name)
            .join(" -> ")}`,
        );
      }
      return false;
    }
    if (resolved.has(task)) return true;

    const deps: PublishTask[] = [];
    const depSet = new Set<PublishTask>();
    const addDep = (dep: PublishTask) => {
      if (!depSet.has(dep)) {
        depSet.add(dep);
        deps.push(dep);
      }
    };
    stackIndex.set(task, stack.length);
    stack.push(task);
    for (const dep of task.wait) {
      if (!taskSet.has(dep)) {
        throw new Error(
          `Task "${task.name}" waits on task "${dep.name}" which is not part of the publish tasks.`,
        );
      }
      stackEdges.push(true);
      if (scan(dep, true)) addDep(dep);
      stackEdges.pop();
    }

    for (const dep of task.optionalWait) {
      if (!taskSet.has(dep) || dep === task) continue;
      stackEdges.push(false);
      if (scan(dep, false)) addDep(dep);
      stackEdges.pop();
    }

    stack.pop();
    stackIndex.delete(task);
    resolved.set(task, deps);
    return true;
  }

  for (const task of tasks) scan(task);
  return resolved;
}

/**
 * Publishes a single package with the shared pipeline: dry-run handling,
 * `willPublish`/`afterPublish` hooks. Thrown failures are captured by the task runner.
 *
 * Providers extend this class and implement `publish()` (and optionally `status()`).
 */
export abstract class PackagePublishTask<
  T extends WorkspacePackage = WorkspacePackage,
> extends PublishTask<PackagePublishTaskResult> {
  name: string;

  constructor(readonly pkg: T) {
    super();
    this.name = `publish:${pkg.id}`;
  }

  /** provider-specific publishing; throw when publishing fails */
  abstract publish(opts: PublishTaskRunContext): Awaitable<PackagePublishTaskResult>;

  /** link publish tasks from preflight `wait`/`optionalWait` data, a package may be published by more than one task */
  link({ plan }: PublishTaskContext): void {
    const preflight = plan.packages.get(this.pkg.id)?.preflight;
    if (!preflight) return;

    // unknown or unpublished dependencies are ignored
    for (const t of plan.tasks) {
      if (!(t instanceof PackagePublishTask) || t === this) continue;
      if (preflight.wait?.includes(t.pkg.id)) this.wait.push(t);
      if (preflight.optionalWait?.includes(t.pkg.id)) this.optionalWait.push(t);
    }
  }

  async run(opts: PublishTaskRunContext): Promise<PackagePublishTaskResult> {
    const { context, plan } = opts;
    const pkg = this.pkg;
    const result = await this.pipeline(opts);
    if (result.type === "skipped") return result;

    for (const plugin of context.plugins) {
      await handlePluginError(plugin, "afterPublish", () =>
        plugin.afterPublish?.call(context, { pkg, plan }),
      );
    }

    return result;
  }

  private async pipeline(opts: PublishTaskRunContext): Promise<PackagePublishTaskResult> {
    const { context, plan } = opts;
    const pkg = this.pkg;
    if (plan.options.dryRun ?? false) {
      return { type: "published" };
    }

    for (const plugin of context.plugins) {
      const next = await handlePluginError(plugin, "willPublish", () =>
        plugin.willPublish?.call(context, { pkg }),
      );

      if (next === false) return { type: "skipped" };
    }

    return await this.publish(opts);
  }
}

/** backward compatibility: publishes a package through the legacy `publish` hook chain */
class LegacyPublishTask extends PackagePublishTask {
  async publish({ context, plan }: PublishTaskRunContext): Promise<PackagePublishTaskResult> {
    const { pkg } = this;

    for (const plugin of context.plugins) {
      const publishResult = await handlePluginError(plugin, "publish", () =>
        plugin.publish?.call(context, { pkg, plan }),
      );

      if (publishResult?.type === "failed") throw new Error(publishResult.error);
      if (publishResult) return publishResult;
    }

    throw new Error(
      `There is no plugin to publish package "${pkg.id}", please make sure the package has a supported provider plugin.`,
    );
  }
}

/** backward compatibility: runs a plugin's `afterPublishAll` hook as a task */
export class PluginAfterPublishAllTask extends PublishTask<void> {
  name: string;

  constructor(
    private readonly plugin: TegamiPlugin,
    previous?: PluginAfterPublishAllTask,
  ) {
    super();
    this.name = `${plugin.name}:after-publish-all`;
    if (previous) this.wait.push(previous);
  }

  /** legacy behaviour: `afterPublishAll` runs after every package publish, including tasks of plugins later in the plugin order */
  link({ plan }: PublishTaskContext): void {
    for (const t of plan.tasks) {
      if (t instanceof PackagePublishTask) this.wait.push(t);
    }
  }

  async run({ context, plan }: PublishTaskRunContext): Promise<void> {
    // legacy behaviour: a failed publish task aborts the `afterPublishAll` hooks
    for (const dep of this.wait) {
      if (dep.getResult()?.status === "failed") return;
    }

    await handlePluginError(this.plugin, "afterPublishAll", () =>
      this.plugin.afterPublishAll!.call(context, { plan }),
    );
  }
}

/** backward compatibility: reports a plugin's `resolvePlanStatus` hook as a task status */
class PluginPlanStatusTask extends PublishTask<void> {
  name: string;

  constructor(private readonly plugin: TegamiPlugin) {
    super();
    this.name = `${plugin.name}:plan-status`;
  }

  run() {}

  async status({ context, plan }: PublishTaskContext) {
    const status = await handlePluginError(this.plugin, "resolvePlanStatus", () =>
      this.plugin.resolvePlanStatus!.call(context, { plan }),
    );

    if (Array.isArray(status)) {
      if (await somePromise(status, (v) => v === "pending")) return "pending" as const;
      return;
    }

    if (status === "pending") return "pending" as const;
    if (status === "success") return "done" as const;
  }
}

export async function collectPublishTasks(
  context: TegamiContext,
  plan: PublishPlan,
): Promise<PublishTask[]> {
  const hookContext = { plan };
  const tasks: PublishTask[] = (plan.tasks = []);
  const packageTasks = new Map<string, { task: PackagePublishTask; plugin: TegamiPlugin }>();
  for (const plugin of context.plugins) {
    const created = await handlePluginError(plugin, "publishTasks", () =>
      plugin.publishTasks?.call(context, hookContext),
    );
    const createdTasks = Array.isArray(created) ? created : [created];
    for (const task of createdTasks) {
      if (!task) continue;

      if (task instanceof PackagePublishTask) {
        if (!plan.packages.get(task.pkg.id)?.preflight?.shouldPublish) {
          throw new Error(
            `Plugin "${plugin.name}" created package publish task "${task.name}" for "${task.pkg.id}", but that package is not selected for publishing.`,
          );
        }

        const existing = packageTasks.get(task.pkg.id);
        if (existing) {
          throw new Error(
            `Package "${task.pkg.id}" has multiple publish tasks: "${existing.task.name}" from plugin "${existing.plugin.name}" and "${task.name}" from plugin "${plugin.name}". Only one PackagePublishTask is allowed per package.`,
          );
        }
        packageTasks.set(task.pkg.id, { task, plugin });
      }

      tasks.push(task);
    }
  }

  // backward compatibility: packages without a publish task go through the legacy `publish` hook chain
  for (const [id, packagePlan] of plan.packages) {
    if (!packagePlan.preflight?.shouldPublish) continue;
    if (packageTasks.has(id)) continue;
    const pkg = context.graph.get(id);
    if (pkg) tasks.push(new LegacyPublishTask(pkg));
  }

  let previousAfterPublishAll: PluginAfterPublishAllTask | undefined;
  for (const plugin of context.plugins) {
    if (plugin.afterPublishAll) {
      const task = new PluginAfterPublishAllTask(plugin, previousAfterPublishAll);
      tasks.push(task);
      previousAfterPublishAll = task;
    }
    if (plugin.resolvePlanStatus) {
      tasks.push(new PluginPlanStatusTask(plugin));
    }
  }

  for (const task of tasks) {
    task.link?.({ context, plan });
  }

  return tasks;
}

export interface PublishOptions {
  /** Validate the publish plan without publishing packages, creating tags, or running release plugins. */
  dryRun?: boolean;

  /**
   * Publish only the given packages and their dependencies.
   *
   * Each entry can be a package id, package name, or `group:name`.
   *
   * When empty, no packages will be published.
   */
  packages?: string[];

  /**
   * The max amount of concurrently running publish tasks (unstable, can change in anytime).
   *
   * @default 5
   */
  unstable_maxChunk?: number;
}

/** Successful outcome returned by a package publish task. Publish failures must be thrown. */
export type PackagePublishTaskResult = {
  type: "published" | "skipped";
};

/** Outcome exposed on a package's publish plan, including failures captured by the task runner. */
export type PackagePublishResult =
  | PackagePublishTaskResult
  | {
      type: "failed";
      error: string;
    };

export async function runPublishPlan(context: TegamiContext, plan: PublishPlan) {
  const { unstable_maxChunk = 5 } = plan.options;

  for (const plugin of context.plugins) {
    await handlePluginError(plugin, "beforePublishAll", () =>
      plugin.beforePublishAll?.call(context, { plan }),
    );
  }

  const tasks = await collectPublishTasks(context, plan);
  await runPublishTasks(tasks, { context, plan, concurrency: unstable_maxChunk });

  const errors = new Set<Error>();
  for (const task of tasks) {
    const state = task.getResult();
    if (state?.status === "failed") errors.add(state.error);
  }
  if (errors.size === 1) throw errors.values().next().value;
  if (errors.size > 1) {
    throw new AggregateError(errors, `${errors.size} publish tasks failed.`);
  }
}

export async function runPreflights(context: TegamiContext, plan: PublishPlan): Promise<void> {
  const { graph } = context;

  await Promise.all(
    Array.from(plan.packages, async ([id, packagePlan]) => {
      const pkg = graph.get(id)!;

      packagePlan.preflight = { shouldPublish: false };
      if (!packagePlan.updated) return;

      for (const plugin of context.plugins) {
        const res = await handlePluginError(plugin, "publishPreflight", () =>
          plugin.publishPreflight?.call(context, { pkg, plan }),
        );

        if (res) {
          packagePlan.preflight = res;
          break;
        }
      }
    }),
  );

  if (plan.options.packages) {
    const only = new Set<string>();
    function addOnly(id: string) {
      if (only.has(id)) return;
      const preflight = plan.packages.get(id)?.preflight;
      if (!preflight) return;

      only.add(id);
      if (preflight.wait) for (const dep of preflight.wait) addOnly(dep);
      if (preflight.optionalWait) for (const dep of preflight.optionalWait) addOnly(dep);
    }

    for (const name of plan.options.packages) {
      for (const pkg of graph.getByName(name)) addOnly(pkg.id);
    }

    for (const [id, packagePlan] of plan.packages) {
      if (only.has(id)) continue;
      packagePlan.preflight!.shouldPublish = false;
    }
  }

  for (const plugin of context.plugins) {
    await handlePluginError(plugin, "afterPreflight", () =>
      plugin.afterPreflight?.call(context, { plan }),
    );
  }
}

export async function publishPlanStatus(
  plan: PublishPlan,
  context: TegamiContext,
): Promise<{
  status: "success" | "pending";
  reason?: string;
}> {
  const tasks = await collectPublishTasks(context, plan);
  const pendingIdx = await findPromiseIndex(
    tasks.map((task) => task.status?.({ context, plan })),
    (check) => check === "pending",
  );

  if (pendingIdx !== -1) {
    return { status: "pending", reason: `Task "${tasks[pendingIdx]!.name}" is pending` };
  }

  return { status: "success" };
}
