import fs from "node:fs/promises";
import { ChangelogEntry, parseChangelogFile } from "../changelog/parse";
import { TegamiContext } from "../context";
import { changelogStoreSchema, packageStoreSchema } from "./draft";
import { parsePublishLock, PublishLock } from "./lock";
import { PublishPreflight } from "../types";
import { WorkspacePackage } from "../graph";
import { handlePluginError } from "../utils/error";

export interface PublishPlan {
  options: PublishOptions;

  /** id -> entry */
  changelogs: Map<string, ChangelogEntry>;
  /** id -> package data. The package id will always exist in package graph, stale items will be pruned at init-time */
  packages: Map<string, PackagePublishPlan>;
}

export interface PackagePublishPlan {
  changelogs: ChangelogEntry[];
  /** whether this package was version-bumped when the lock was written */
  updated: boolean;

  /** generated by Git plugin */
  git?: {
    /** the associated Git tag of package */
    tag?: string;
  };

  /** generated by npm plugin */
  npm?: {
    /** dist tag to use if published */
    distTag?: string;
  };

  /** publish result, generated for all packages in publish plan after publishing */
  publishResult?: PackagePublishResult;

  /** preflight result, generated for all packages in publish plan after preflights */
  preflight?: PublishPreflight;
}

export async function initPublishPlan(
  context: TegamiContext,
  options: PublishOptions,
): Promise<PublishPlan | undefined> {
  let lock: PublishLock;
  try {
    lock = parsePublishLock(await fs.readFile(context.lockPath, "utf8"));
  } catch {
    return;
  }

  let data: unknown;
  const packages = new Map<string, PackagePublishPlan>();
  const changelogs = new Map<string, ChangelogEntry>();

  while ((data = lock.read("core:changelogs"))) {
    const entry = changelogStoreSchema.safeParse(data).data;
    if (!entry) continue;
    const parsed = parseChangelogFile(entry.filename, entry.content);
    if (!parsed) continue;

    changelogs.set(parsed.id, parsed);
  }

  while ((data = lock.read("core:packages"))) {
    const parsed = packageStoreSchema.safeParse(data).data;
    if (!parsed) continue;
    if (!context.graph.get(parsed.id)) continue;

    const pkgChangelogs: ChangelogEntry[] = [];
    for (const id of parsed.changelogIds ?? []) {
      const entry = changelogs.get(id);
      if (entry) pkgChangelogs.push(entry);
    }
    packages.set(parsed.id, { changelogs: pkgChangelogs, updated: parsed.updated });
  }

  const plan: PublishPlan = {
    options,
    changelogs,
    packages,
  };

  for (const plugin of context.plugins) {
    await handlePluginError(plugin, "initPublishPlan", () =>
      plugin.initPublishPlan?.call(context, { lock, plan }),
    );
  }

  return plan;
}

function resolvePublishTargets(plan: PublishPlan): string[] {
  const ordered: string[] = [];

  function scan(id: string, stack = new Set<string>()) {
    const preflight = plan.packages.get(id)?.preflight;
    if (!preflight || !preflight.publish) return;

    if (stack.has(id)) {
      throw new Error(`circular reference of deps: ${[...stack, id].join(" -> ")}`);
    }

    if (ordered.includes(id)) return;

    if (preflight.wait) {
      stack.add(id);
      for (const dep of preflight.wait) scan(dep, stack);
      stack.delete(id);
    }

    ordered.push(id);
  }

  for (const id of plan.packages.keys()) scan(id);
  return ordered;
}

export interface PublishOptions {
  /** Validate the publish plan without publishing packages, creating tags, or running release plugins. */
  dryRun?: boolean;
}

export type PackagePublishResult =
  | {
      type: "published" | "skipped";
    }
  | {
      type: "failed";
      error: string;
    };

export async function runPublishPlan(context: TegamiContext, plan: PublishPlan) {
  const { dryRun = false } = plan.options;

  const onPublishResult = async (pkg: WorkspacePackage, publishResult: PackagePublishResult) => {
    const packagePlan = plan.packages.get(pkg.id);
    if (!packagePlan) return;
    packagePlan.publishResult = publishResult;
    if (publishResult.type === "skipped") return;

    for (const plugin of context.plugins) {
      await handlePluginError(plugin, "afterPublish", () =>
        plugin.afterPublish?.call(context, {
          pkg,
          plan,
        }),
      );
    }
  };

  publishLoop: for (const id of resolvePublishTargets(plan)) {
    const pkg = context.graph.get(id)!;

    if (dryRun) {
      await onPublishResult(pkg, {
        type: "published",
      });
      continue;
    }

    for (const plugin of context.plugins) {
      const next = await handlePluginError(plugin, "willPublish", () =>
        plugin.willPublish?.call(context, { pkg }),
      );

      if (next === false) {
        continue publishLoop;
      }
    }

    for (const plugin of context.plugins) {
      const publishResult = await handlePluginError(plugin, "publish", () =>
        plugin.publish?.call(context, { pkg, plan }),
      );

      if (publishResult) {
        await onPublishResult(pkg, publishResult);
        continue publishLoop;
      }
    }

    await onPublishResult(pkg, {
      type: "failed",
      error: `There is no plugin to publish package "${pkg.id}", please make sure the package has a supported provider plugin.`,
    });
  }

  for (const packagePlan of plan.packages.values()) {
    packagePlan.publishResult ??= {
      type: "skipped",
    };
  }

  for (const plugin of context.plugins) {
    await handlePluginError(plugin, "afterPublishAll", () =>
      plugin.afterPublishAll?.call(context, { plan }),
    );
  }
}

export async function runPreflights(context: TegamiContext, plan: PublishPlan): Promise<void> {
  const promises: Promise<void>[] = [];

  const runPreflight = async (pkg: WorkspacePackage) => {
    const out: PublishPreflight = {
      publish: true,
    };

    for (const plugin of context.plugins) {
      const res = await handlePluginError(plugin, "publishPreflight", () =>
        plugin.publishPreflight?.call(context, { pkg, plan }),
      );

      if (res === undefined) continue;

      out.publish = res.publish;
      if (res.wait) {
        out.wait ??= [];
        out.wait.push(...res.wait);
      }
    }
    return out;
  };

  for (const [id, packagePlan] of plan.packages) {
    const pkg = context.graph.get(id)!;

    if (!packagePlan.updated) {
      packagePlan.preflight = { publish: false };
      continue;
    }

    promises.push(
      runPreflight(pkg).then((preflight) => {
        packagePlan.preflight = preflight;
      }),
    );
  }

  await Promise.all(promises);
}

export async function publishPlanStatus(
  plan: PublishPlan,
  context: TegamiContext,
): Promise<"success" | "pending"> {
  for (const pkg of plan.packages.values()) {
    if (!pkg.preflight) throw new Error("Should perform preflight before checking plan status.");

    if (pkg.preflight.publish) return "pending";
  }

  try {
    await Promise.all(
      context.plugins.map(async (plugin) => {
        const status = await handlePluginError(plugin, "resolvePlanStatus", () =>
          plugin.resolvePlanStatus?.call(context, { plan }),
        );

        if (status === "pending") throw "pending";
      }),
    );

    return "success";
  } catch (e) {
    if (e === "pending") return "pending";
    throw e;
  }
}
