import fs from "node:fs/promises";
import { ChangelogEntry, parseChangelogFile } from "../changelog/parse";
import { TegamiContext } from "../context";
import { validateChangelogStore, validatePackageStore } from "./draft";
import { parsePublishLock, PublishLock } from "./lock";
import { PublishPreflight } from "../types";
import { WorkspacePackage } from "../graph";
import { handlePluginError } from "../utils/error";
import { somePromise } from "../utils/common";

export interface PublishPlan {
  options: PublishOptions;

  /** id -> entry */
  changelogs: Map<string, ChangelogEntry>;
  /** id -> package data. The package id will always exist in package graph, stale items will be pruned at init-time */
  packages: Map<string, PackagePublishPlan>;
}

export interface PackagePublishPlan {
  changelogs: ChangelogEntry[];
  /** whether this package was version-bumped when the lock was written */
  updated: boolean;

  /** generated by Git plugin */
  git?: {
    /** the associated Git tag of package */
    tag?: string;
  };

  /** generated by npm plugin */
  npm?: {
    /** dist tag to use if published */
    distTag?: string;

    /** point latest tag to it if published */
    markLatest?: boolean;
  };

  /** publish result, generated for all packages in publish plan after publishing */
  publishResult?: PackagePublishResult;

  /** preflight result, generated for all packages in publish plan after preflights */
  preflight?: PublishPreflight;
}

export async function initPublishPlan(
  context: TegamiContext,
  options: PublishOptions,
): Promise<PublishPlan | undefined> {
  let lock: PublishLock;
  try {
    lock = parsePublishLock(await fs.readFile(context.lockPath, "utf8"));
  } catch {
    return;
  }

  let data: unknown;
  const packages = new Map<string, PackagePublishPlan>();
  const changelogs = new Map<string, ChangelogEntry>();

  while ((data = lock.read("core:changelogs"))) {
    const validated = validateChangelogStore(data);
    if (!validated.success) continue;
    const entry = validated.data;
    const parsed = parseChangelogFile(entry.filename, entry.content);
    if (!parsed) continue;

    changelogs.set(parsed.id, parsed);
  }

  while ((data = lock.read("core:packages"))) {
    const validated = validatePackageStore(data);
    if (!validated.success) continue;
    const parsed = validated.data;
    if (!context.graph.get(parsed.id)) continue;

    const pkgChangelogs: ChangelogEntry[] = [];
    for (const id of parsed.changelogIds ?? []) {
      const entry = changelogs.get(id);
      if (entry) pkgChangelogs.push(entry);
    }
    packages.set(parsed.id, { changelogs: pkgChangelogs, updated: parsed.updated });
  }

  const plan: PublishPlan = {
    options,
    changelogs,
    packages,
  };

  for (const plugin of context.plugins) {
    await handlePluginError(plugin, "initPublishPlan", () =>
      plugin.initPublishPlan?.call(context, { lock, plan }),
    );
  }

  return plan;
}

function resolvePublishTargets(plan: PublishPlan) {
  /** the iteration order = publish order */
  const orderedMap = new Map<string, { split: boolean }>();
  const stack = new Set<string>();

  function scan(id: string) {
    const preflight = plan.packages.get(id)?.preflight;
    if (!preflight || !preflight.shouldPublish) return;

    if (stack.has(id)) {
      throw new Error(`circular reference of deps: ${[...stack, id].join(" -> ")}`);
    }

    if (orderedMap.has(id)) return;

    let split = false;
    if (preflight.wait) {
      stack.add(id);
      split ||= preflight.wait.length > 0;
      for (const dep of preflight.wait) scan(dep);
      stack.delete(id);
    }

    if (preflight.optionalWait) {
      split ||= preflight.optionalWait.length > 0;
      for (const dep of preflight.optionalWait) scan(dep);
    }

    orderedMap.set(id, { split });
  }

  for (const id of plan.packages.keys()) scan(id);
  return orderedMap;
}

export interface PublishOptions {
  /** Validate the publish plan without publishing packages, creating tags, or running release plugins. */
  dryRun?: boolean;

  /**
   * Publish only the given packages and their dependencies.
   *
   * Each entry can be a package id, package name, or `group:name`.
   */
  packages?: string[];

  /**
   * The max amount of concurrent publishes (unstable, can change in anytime).
   *
   * @default 5
   */
  unstable_maxChunk?: number;
}

export type PackagePublishResult =
  | {
      type: "published" | "skipped";
    }
  | {
      type: "failed";
      error: string;
    };

export async function runPublishPlan(context: TegamiContext, plan: PublishPlan) {
  const { dryRun = false, unstable_maxChunk = 5 } = plan.options;

  async function publish(pkg: WorkspacePackage): Promise<PackagePublishResult> {
    if (dryRun) {
      return { type: "published" };
    }

    try {
      for (const plugin of context.plugins) {
        const next = await handlePluginError(plugin, "willPublish", () =>
          plugin.willPublish?.call(context, { pkg }),
        );

        if (next === false) return { type: "skipped" };
      }

      for (const plugin of context.plugins) {
        const publishResult = await handlePluginError(plugin, "publish", () =>
          plugin.publish?.call(context, { pkg, plan }),
        );

        if (publishResult) return publishResult;
      }
    } catch (e) {
      return {
        type: "failed",
        error: e instanceof Error ? e.message : String(e),
      };
    }

    return {
      type: "failed",
      error: `There is no plugin to publish package "${pkg.id}", please make sure the package has a supported provider plugin.`,
    };
  }

  let promises: Promise<void>[] = [];
  for (const [id, { split }] of resolvePublishTargets(plan)) {
    const pkg = context.graph.get(id)!;
    const packagePlan = plan.packages.get(pkg.id);
    if (!pkg || !packagePlan) continue;

    if (split || promises.length >= unstable_maxChunk) {
      await Promise.all(promises);
      promises = [];
    }

    promises.push(
      publish(pkg).then(async (result) => {
        packagePlan.publishResult = result;
        if (result.type === "skipped") return;

        for (const plugin of context.plugins) {
          await handlePluginError(plugin, "afterPublish", () =>
            plugin.afterPublish?.call(context, {
              pkg,
              plan,
            }),
          );
        }
      }),
    );
  }

  await Promise.all(promises);
  for (const packagePlan of plan.packages.values()) {
    packagePlan.publishResult ??= {
      type: "skipped",
    };
  }

  for (const plugin of context.plugins) {
    await handlePluginError(plugin, "afterPublishAll", () =>
      plugin.afterPublishAll?.call(context, { plan }),
    );
  }
}

export async function runPreflights(context: TegamiContext, plan: PublishPlan): Promise<void> {
  const { graph } = context;

  await Promise.all(
    Array.from(plan.packages, async ([id, packagePlan]) => {
      const pkg = graph.get(id)!;

      packagePlan.preflight = { shouldPublish: false };
      if (!packagePlan.updated) return;

      for (const plugin of context.plugins) {
        const res = await handlePluginError(plugin, "publishPreflight", () =>
          plugin.publishPreflight?.call(context, { pkg, plan }),
        );

        if (res) {
          packagePlan.preflight = res;
          break;
        }
      }
    }),
  );

  if (plan.options.packages?.length) {
    const only = new Set<string>();
    function addOnly(id: string) {
      if (only.has(id)) return;
      const preflight = plan.packages.get(id)?.preflight;
      if (!preflight) return;

      only.add(id);
      if (preflight.wait) for (const dep of preflight.wait) addOnly(dep);
      if (preflight.optionalWait) for (const dep of preflight.optionalWait) addOnly(dep);
    }

    for (const name of plan.options.packages) {
      for (const pkg of graph.getByName(name)) addOnly(pkg.id);
    }

    for (const [id, packagePlan] of plan.packages) {
      if (only.has(id)) continue;
      packagePlan.preflight!.shouldPublish = false;
    }
  }

  for (const plugin of context.plugins) {
    await handlePluginError(plugin, "afterPreflight", () =>
      plugin.afterPreflight?.call(context, { plan }),
    );
  }
}

export async function publishPlanStatus(
  plan: PublishPlan,
  context: TegamiContext,
): Promise<"success" | "pending"> {
  for (const plugin of context.plugins) {
    const status = await handlePluginError(plugin, "resolvePlanStatus", () =>
      plugin.resolvePlanStatus?.call(context, { plan }),
    );

    if (Array.isArray(status) && (await somePromise(status, (v) => v === "pending"))) {
      return "pending";
    }

    if (status === "pending") {
      return "pending";
    }
  }

  return "success";
}
